image: node:16

pipelines:
  default:
    - step:
        name: Install, build dictionary, lint, format, and test
        script:
          - cd client
          - npm install
          - npm run build-dictionary
          - npm run lint
          - npm run format
          - npm test
        caches:
          - node
  branches:
    main:
      - step:
          name: set up client release
          caches:
            - node
          script:
            - cd client
            - npm install
            - npm test
            - npx semantic-release --no-ci
