pipelines:
  default:
    - step:
        name: Client - Install, build dictionary, lint, format, and test
        image: node:16
        script:
          - cd client
          - npm install
          - npm run build-dictionary
          - npm run lint
          - npm run format
          - npm test
        caches:
          - node
    - step:
        name: Server - Install, lint, format, and test
        image: php:8.1-fpm
        script:
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - cd server
          - composer install
          - vendor/bin/phpcs -h
          - vendor/bin/phpcbf -h
          - vendor/bin/php-cs-fixer fix ./
          - vendor/bin/phpunit tests
  branches:
    main:
      - step:
          image: node:16
          caches:
            - node
          script:
            - apt-get update && apt-get install -y curl jq
            - >
              export BB_TOKEN=$(curl -s -X POST -u "${CLIENT_ID}:${CLIENT_SECRET}" \
                https://bitbucket.org/site/oauth2/access_token \
                -d grant_type=client_credentials -d scopes="repository"| jq --raw-output '.access_token')
            - cd client
            - npm install
            - npm test
            - npx semantic-release --no-ci
