image: node:16

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - cd client
              - npm install
              - npm test
        - step:
            name: Code linting and formatting
            script:
              - cd client
              - npm install
              - npm run lint
              - npm run format
            caches:
              - node
        - step:
            name: Build style dictionary
            script:
              - cd client
              - npm install
              - npm run build-dictionary
            caches:
              - node
