version: "3.8"
services:
    nginx:
        image: nginx:alpine
        container_name: nginx-container
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        environment:
            ENABLE_CORS: true
        ports:
            - 8000:80
            - 80:80
            - 443:443
        links:
            - php
        volumes:
            - ./server:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        networks:
            - app-network
    certbot:
        image: certbot/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
    php:
        build: .
        container_name: php-container
        links:
            - mysql
        volumes:
            - .env:/var/www/.env
            - ./server:/var/www
        networks:
            - app-network
    mysql:
        image: mysql:8
        container_name: mysql-container
        ports:
            - 3306:3306
        volumes:
            - ./db:/var/lib/mysql
        env_file: './.env'
        networks:
            - app-network
    composer:
        image: composer:2.3
        container_name: composer-container
        volumes:
            - ./server:/app
        command: ["composer", "install"]

networks:
    app-network:
        driver: bridge
