version: "3.8"
services:
    nginx:
        image: nginx:alpine
        container_name: nginx-container
        environment:
            ENABLE_CORS: true
        ports:
            - 8000:80
            - 80:80
            - 443:443
        links:
            - php
        volumes:
            - ./server:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./certs:/etc/nginx/certs
        networks:
            - app-network
    php:
        build: .
        container_name: php-container
        links:
            - mysql
        volumes:
            - .env:/var/www/.env
            - ./server:/var/www
        networks:
            - app-network
    mysql:
        image: mysql:8
        container_name: mysql-container
        ports:
            - 3306:3306
        volumes:
            - ./db:/var/lib/mysql
        env_file: './.env'
        networks:
            - app-network
    composer:
        image: composer:2.3
        container_name: composer-container
        command: ["composer", "install"]
        volumes:
            - ./server:/var/www

networks:
    app-network:
        driver: bridge
